
[module]
  name = "FullInventoryAlternating"

[[module.statics]]
  name = "FullInventoryAlternating_Static"
  file = "FullInventoryAlternating.lyn.event"

[[module.dynamics]]
  name = "FullInventoryAlternating_Dynamic"
  file = "FullInventoryAlternating.lyn.event"

[[module.definitions]]
  name = "INVENTORY_ICON_X"
  value = 40

[[module.definitions]]
  name = "INVENTORY_ICON_Y"
  value = 8

[[module.definitions]]
  name = "INVENTORY_ICON_BASE_TILE"
  value = 0x0300

[[module.definitions]]
  name = "INVENTORY_ICON_PALETTE"
  value = 20

[[module.definitions]]
  name = "INVENTORY_ALTERNATE_FRAMES"
  value = 64

[[module.definitions]]
  name = "ITEM_ICON_PAGE"
  value = 0

[[module.definitions]]
  name = "ItemIconPalettes"
  body = '''
enum ItemIconPalettes
{
  ITEM_ICON_PALETTE_ITEMS,
  ITEM_ICON_PALETTE_AFFINITIES,
};
'''

[[module.asm_definitions]]
  name = "NEED_aeabi_uidivmod"
  value = 1

[[module.internals]]
  file = "LibraryFunctions/LibraryFunctions.event"


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x08004AC8 | 1"
  games = [ "FE6J" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x08004DD8 | 1"
  games = [ "FE6J" ]

[[module.asm_definitions]]
  name = "GetItemIconId"
  body = "SET_FUNC GetItemIconId, 0x080172D8 | 1"
  games = [ "FE6J" ]

[[module.asm_definitions]]
  name = "GetUnitItemCount"
  body = "SET_FUNC GetUnitItemCount, 0x08017520 | 1"
  games = [ "FE6J" ]


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x08004D44 | 1"
  games = [ "FE7U" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x08004E98 | 1"
  games = [ "FE7U" ]

[[module.asm_definitions]]
  name = "GetItemIconId"
  body = "SET_FUNC GetItemIconId, 0x08017400 | 1"
  games = [ "FE7U" ]

[[module.asm_definitions]]
  name = "GetUnitItemCount"
  body = "SET_FUNC GetUnitItemCount, 0x080176DC | 1"
  games = [ "FE7U" ]


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x08004C20 | 1"
  games = [ "FE7J" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x08004D74 | 1"
  games = [ "FE7J" ]

[[module.asm_definitions]]
  name = "GetItemIconId"
  body = "SET_FUNC GetItemIconId, 0x08017808 | 1"
  games = [ "FE7J" ]

[[module.asm_definitions]]
  name = "GetUnitItemCount"
  body = "SET_FUNC GetUnitItemCount, 0x08017ACC | 1"
  games = [ "FE7J" ]


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x080035D4 | 1"
  games = [ "FE8U" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x0800372C | 1"
  games = [ "FE8U" ]

[[module.asm_definitions]]
  name = "GetItemIconId"
  body = "SET_FUNC GetItemIconId, 0x08017700 | 1"
  games = [ "FE8U" ]

[[module.asm_definitions]]
  name = "GetUnitItemCount"
  body = "SET_FUNC GetUnitItemCount, 0x080179D8 | 1"
  games = [ "FE8U" ]


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x08003520 | 1"
  games = [ "FE8J" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x08003678 | 1"
  games = [ "FE8J" ]

[[module.asm_definitions]]
  name = "GetItemIconId"
  body = "SET_FUNC GetItemIconId, 0x080174A8 | 1"
  games = [ "FE8J" ]

[[module.asm_definitions]]
  name = "GetUnitItemCount"
  body = "SET_FUNC GetUnitItemCount, 0x08017780 | 1"
  games = [ "FE8J" ]
