[package]
name = "neleras"
description = "The GORGON-EGG tilemap converter"
license = "MIT"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
anyhow = "1.0.98"
tiled = "0.15.0"
itertools = "0.14.0"
