
[module]
  name = "Affinity"

[[module.statics]]
  name = "Affinity_Static"
  file = "Affinity.lyn.event"

[[module.dynamics]]
  name = "Affinity_Dynamic"
  file = "Affinity.lyn.event"

[[module.definitions]]
  name = "AFFINITY_X"
  value = 40

[[module.definitions]]
  name = "AFFINITY_Y"
  value = 8

[[module.definitions]]
  name = "AFFINITY_PAGE"
  value = 0

[[module.definitions]]
  name = "AFFINITY_BASE_TILE"
  value = 0x030A

[[module.definitions]]
  name = "AFFINITY_PALETTE"
  value = 21

[[module.definitions]]
  name = "ItemIconPalettes"
  body = '''
enum ItemIconPalettes
{
  ITEM_ICON_PALETTE_ITEMS,
  ITEM_ICON_PALETTE_AFFINITIES,
};
'''


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x08004AC8 | 1"
  games = [ "FE6J" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x08004DD8 | 1"
  games = [ "FE6J" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x08022F44 | 1"
  games = [ "FE6J" ]


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x08004D44 | 1"
  games = [ "FE7U" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x08004E98 | 1"
  games = [ "FE7U" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x08026B24 | 1"
  games = [ "FE7U" ]


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x08004C20 | 1"
  games = [ "FE7J" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x08004D74 | 1"
  games = [ "FE7J" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x08026FB0 | 1"
  games = [ "FE7J" ]


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x080035D4 | 1"
  games = [ "FE8U" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x0800372C | 1"
  games = [ "FE8U" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x080286BC | 1"
  games = [ "FE8U" ]


[[module.asm_definitions]]
  name = "LoadIconPalette"
  body = "SET_FUNC LoadIconPalette, 0x08003520 | 1"
  games = [ "FE8J" ]

[[module.asm_definitions]]
  name = "LoadIconObjectGraphics"
  body = "SET_FUNC LoadIconObjectGraphics, 0x08003678 | 1"
  games = [ "FE8J" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x08028650 | 1"
  games = [ "FE8J" ]
